name: norminette

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run norminette
        uses: alexandregv/norminette-action@v3
        with:
          flags: '.'
